src/accounts/urls.py
#from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'accounts'
urlpatterns = [
    url('login/', views.LoginView.as_view(), name="login"),
    url('logout/', views.LogoutView.as_view(), name='logout'),
    url('signup/', views.SignUpView.as_view(), name='signup'),
    url('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    url('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    url('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    url('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/demos/urls.py
from django.conf.urls import include, url
from django.conf.urls import handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import estadistica.urls
import maquetas.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = 'Demos Site Admin'
admin.site.site_header = 'Demos Administration'

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url('', include(accounts.urls)),
    url(r'^estadistica/', include(estadistica.urls, namespace='estadistica')),
    url(r'^poc/', include(maquetas.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url('__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/templates/_brandname.html
Demos

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
{% load staticfiles %}
{% load thumbnail %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Mundo Pixel">
    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link href="{% static 'site/css/style.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .dropbtn {
            background-color: #3498DB;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        .dropbtn:hover, .dropbtn:focus {
            background-color: #2980B9;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown a:hover {
            background-color: #f1f1f1
        }

        .show {
            display: block;
        }
    </style>
    {% block styles %}
    {% endblock styles %}

    {% block extrahead %}
    {% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- HEADER DE PAGE -->
<header id="header" style="background: #717171">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <nav class="left">
                    <a href="#menu"><span>Menu</span></a>
                </nav>
            </div>
            <div class="col-md-4">
                <a href="{% url 'home' %}" class="logo">
                    <img src="{% static 'site/img/logo-soa.png' %}" class="img-responsive" alt="SOAPros">
                </a>
            </div>
            <div class="col-md-4">
                <nav class="right">
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}

                        {% endif %}
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="profile-menu"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}"
                                     alt=""/>
                                {{ user.get_full_name|truncatechars:20 }}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'profiles:show_self' %}">Mi perfil</a></li>
                                <li><a href="{% url 'accounts:logout' %}">Cerrar sesión</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="btn btn-default">Iniciar Sesión  <i class="fa fa-sign-in"
                                                                                        aria-hidden="true"></i></a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
</header>

<!-- MENU DE PAGE -->
<nav id="menu">
    {% block navbar %}
        <ul class="links">
            {% include "_navbar.html" with active_link="home" %}
            <!--<li><a href="home.html">Inicio</a></li>
            <li><a href="generic.html">Sobre Nosotros</a></li>
            <li><a href="elements.html">Contacto</a></li>-->
        </ul>
        <ul class="actions vertical">
            {% if user.is_authenticated %}
                {% if user.is_staff %}

                {% endif %}
                <div class="dropdown">
                    <a onclick="myFunction()" class="dropdown-toggle profile-sidebar"><img
                            src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}"
                            alt=""/>   {{ user.get_full_name|truncatechars:20 }}
                        <span class="caret"></span></a>
                    <div id="myDropdown" class="dropdown-content">
                        <a href="{% url 'profiles:show_self' %}">Mi perfil</a>
                        <a href="{% url 'accounts:logout' %}">Cerrar sesión</a>
                    </div>
                </div>
                <!--
                <div class="dropdown">
                    <a href="#" class="dropdown-toggle profile-sidebar" data-toggle="dropdown" id="dropbtn">
                        <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}"
                             alt=""/>
                        {{ user.get_full_name|truncatechars:20 }}
                        <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'profiles:show_self' %}">Mi perfil</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Cerrar sesión</a></li>
                    </ul>
                </div>
                -->
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-default"><i class="fa fa-sign-in"
                                                                                aria-hidden="true"></i></a>
            {% endif %}
        </ul>
    {% endblock navbar %}
</nav>

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block splash %}
{% endblock splash %}

<div class="page">
    {% block container %}

    {% endblock container %}
</div>
{% block footer %}
    <!-- FOOTER -->
    <footer id="footer">
        <div class="inner">
            <h2>Contáctenos</h2>
            <ul class="actions">
                <li><span class="icon fa-phone"></span> Telf. +51 (01) 725 7420</li>
                <li><span class="icon fa-envelope"></span> <a href="#">contactp@soapros.pe</a></li>
                <li><span class="icon fa-map-marker"></span> Calle Santander 186 Of. 401 Miraflores, Lima</li>
            </ul>
        </div>
        <div class="copyright">
            &copy; <a href=""> SOA Professionals</a> - Derechos reservados.
        </div>
    </footer>
{% endblock %}

<!-- SCRIPTS TEMPLATES -->
<script src="{% static 'components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'site/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'site/js/skel.min.js' %}"></script>
<script src="{% static 'site/js/util.js' %}"></script>
<script src="{% static 'site/js/main.js' %}"></script>

<script>
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn')) {

            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

{% block scripts %}
{% endblock scripts %}
</body>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Inicio{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<!--<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>-->
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}

{% endblock splash %}

{% block container %}

    <!-- BANNER PRINCIPAL -->
			<section id="banner">
				<div class="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-7">
                                <div class="panel-welcome">
                                    <h1>Acerca de nosotros</h1>
                                    <p>
                                        Empresa de Tecnología enfocada en la gestión de las comunicaciones y como la Inteligencia Artificial puede ayudar a las empresas.
                                    </p>
                                    <ul class="actions">
                                        <li><a href="#one" class="button scrolly">Conoce nuestro producto</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <!--<img class="img-responsive" src="{% static 'site/img/phone.png' %}">-->
                            </div>
                        </div>

                    </div>
				</div>
			</section>

    <!-- SECCION UNO -->
<!--
			<section id="one" class="wrapper">
                <div class="title">
                    <h2>Especialistas en tecnología educativa</h2>
                </div>
				<div class="inner flex flex-3">
					<div class="flex-item left">
						<div>
							<h3>Super fácil de usar</h3>
							<p>Interfaz gráfica amigable, moderna e intuitiva, para un manejo rápido de tus procesos.</p>
						</div>
						<div>
							<h3>Reducción de tiempos y costos</h3>
                            <p>Generé estadísticas, cálculos, promedios, reportes académicos de la manera más sencilla y rápida.</p>

						</div>
					</div>
					<div class="flex-item image fit round">
						<img class="img-responsive" src="{% static 'site/img/laptop_app.png' %}" alt="Apps" />
					</div>
					<div class="flex-item right">
						<div>
							<h3>Soporte 24/7 siempre</h3>
							<p>Soporte Técnico 24/7, todos los usuarios acceden a información útil actualizada al momento para el manejo de los módulos.</p>
						</div>
						<div>
							<h3>No requiere inversión adicional</h3>
                            <p>No requiere de software o hardware adicional ya que nuestra plataforma utiliza los servicios cloud (Amazón, Azure)</p>
						</div>
					</div>
				</div>
			</section>
			-->
    <!-- SECCION DOS -->

<!--
			<section id="two" class="wrapper style1 special">
				<div class="inner">
					<h2>Integra a toda la comunidad educativa en un sola APP</h2>
					<figure>
					    <blockquote>
					        Brindamos soluciones tecnológicas en el campo educativo, permitiendo mejorar y agilizar los procesos administrativos y pedagógicos de tu institución educativa.
Todo esto a través de nuestro módulo de gestión de facturación, Académico, Agenda Escolar, reportes de asistencias y pagos de pensión, calendario y horarios académicos, entre otros.

					    </blockquote>
					    <div class="text-center">
                            <img class="img-responsive" src="{% static 'site/img/app_movil.png' %}">
                        </div>
                        <div class="data-center">
                            Mundo Pixel S.A.C garantiza su confianza y seguridad al estar hospedado en
                            los mejores servidores del mercado, como lo son Amazon y Microsoft Azure.
                            <div class="server">
                                <img src="{% static 'site/img/logo_amazon.png' %}">
                                <img src="{% static 'site/img/logo_azure.png' %}">
                            </div>
                        </div>
					</figure>
				</div>
			</section>
			-->
    <!-- SECCION TRES -->
			<section id="three" class="wrapper">
				<div class="inner flex flex-3">
					<div class="flex-item box">
						<div class="image fit">
							<img src="{% static 'site/img/responsive-website-designers.jpg' %}" alt="CCM" />
						</div>
						<div class="content">
							<h3>PoC CCM</h3>
							<p>Conozca los beneficios que pueda encontrar en el uso de CCM en su empresa, llegué de una
								mejor manera a sus clientes comunicando más efectivamente.</p>
						</div>

						<ul>
							<li><a href="http://demos.soapros.pe/poc/claro/">PoC Claro</a></li>

							<li><a href="http://demos.soapros.pe/poc/vivo/" >PoC Vivo</a></li>

							<li><a href="http://demos.soapros.pe/poc/tim/">PoC Tim</a></li>

                            <li><a href="http://demos.soapros.pe/estadistica/demo/">Control Clicks Recibo </a> </li>
						</ul>

					</div>
					<!--
					<div class="flex-item box">
						<div class="image fit">
							<img src="{% static 'site/img/agenda.jpg' %}" alt="IA" />
						</div>
						<div class="content">
							<h3>PoC IA</h3>
							<p>Mire lo que la IA artificial puede darle a su negocio, anticipese a los hechos,
							encuentre nuevas formas de explotar toda la información con la que cuenta</p>
						</div>
					</div>
					<div class="flex-item box">
						<div class="image fit">
							<img src="{% static 'site/img/banner3.jpg' %}" alt="Otros" />
						</div>
						<div class="content">
							<h3>Otras PoC</h3>
							<p>Otros desarrollos que muestran como la tecnología es un facilitador</p>
						</div>
					</div>
					-->
				</div>
			</section>
{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}